version: '3.0'
services:
  spring-db:
    container_name: "pulsary-mysql"
    image: mysql:8.2.0-oracle 
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"

  adminer:
    container_name: "pulsary-adminer"
    image: adminer
    ports:
      - "8080:8080"
